### ISSUE TITLE
Great project here! Some compiling errors for Cinder_0.8.6 though...

### ISSUE THREAD

**Issue by frantic0** [smallab/CCGLTouch#3]
Hi Mathiew!

Great project here! It is just what I needed to help me with my next app! 

I followed your instructions "Download the CCGLTouch examples package. Unzip the file and place the "CCGLTouch" you obtain at the root of your Cinder folder, besides "samples", "blocks", "lib"..."

however AudioToolbox.framework wasn't included in build phases in the link binary with libraries so I added it manually. Then I got this error bellow.. I suspect that this because I'm using Cinder_0.8.6. How can I overcome this? Many thanks.

Best,
F 

Ld /Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Products/Debug-iphonesimulator/CCGLTouchTabs.app/CCGLTouchTabs normal i386
    cd /Users/francisco/Documents/Development/Cinder/Cinder_0.8.6/CCGLTouch/CCGLTouchTabs
    export IPHONEOS_DEPLOYMENT_TARGET=5.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Products/Debug-iphonesimulator -F/Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Products/Debug-iphonesimulator -filelist /Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Intermediates/CCGLTouchTabs.build/Debug-iphonesimulator/CCGLTouchTabs.build/Objects-normal/i386/CCGLTouchTabs.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 ../../lib/libcinder-iphone-sim_d.a -lz -stdlib=libc++ -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.0 -framework UIKit -framework Foundation -framework CoreGraphics -framework QuartzCore -framework OpenGLES -framework AudioToolbox -framework CoreVideo -framework AVFoundation -framework CoreMedia -framework CoreText -framework MobileCoreServices -framework ImageIO -Xlinker -dependency_info -Xlinker /Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Intermediates/CCGLTouchTabs.build/Debug-iphonesimulator/CCGLTouchTabs.build/Objects-normal/i386/CCGLTouchTabs_dependency_info.dat -o /Users/francisco/Library/Developer/Xcode/DerivedData/CCGLTouchTabs-clyvkvpgydespadyhbdbfzovpmqv/Build/Products/Debug-iphonesimulator/CCGLTouchTabs.app/CCGLTouchTabs

Undefined symbols for architecture i386:
  "_create_fftsetup", referenced from:
      cinder::audio::dsp::Fft::init() in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_ctoz", referenced from:
      cinder::audio::dsp::Fft::forward(cinder::audio::BufferT<float> const_, cinder::audio::BufferSpectralT<float>_) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_destroy_fftsetup", referenced from:
      cinder::audio::dsp::Fft::~Fft() in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_fft_zrip", referenced from:
      cinder::audio::dsp::Fft::forward(cinder::audio::BufferT<float> const_, cinder::audio::BufferSpectralT<float>_) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_fft_zrop", referenced from:
      cinder::audio::dsp::Fft::inverse(cinder::audio::BufferSpectralT<float> const_, cinder::audio::BufferT<float>_) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_deq22D", referenced from:
      cinder::audio::dsp::Biquad::processSliceVDsp(double_, double_, double_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_rmsqv", referenced from:
      cinder::audio::dsp::rms(float const_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_svemg", referenced from:
      cinder::audio::dsp::sum(float const_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_vasm", referenced from:
      cinder::audio::dsp::addMul(float const_, float const_, float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_vdiv", referenced from:
      cinder::audio::dsp::divide(float const_, float const_, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_vfill", referenced from:
      cinder::audio::dsp::fill(float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_vsadd", referenced from:
      cinder::audio::dsp::add(float const_, float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
      cinder::audio::dsp::sub(float const_, float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vDSP_vsdiv", referenced from:
      cinder::audio::dsp::divide(float const_, float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vadd", referenced from:
      cinder::audio::dsp::add(float const_, float const_, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vmul", referenced from:
      cinder::audio::dsp::mul(float const_, float const_, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vsmul", referenced from:
      cinder::audio::dsp::Fft::inverse(cinder::audio::BufferSpectralT<float> const_, cinder::audio::BufferT<float>_) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
      cinder::audio::dsp::mul(float const_, float, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_vsub", referenced from:
      cinder::audio::dsp::sub(float const_, float const_, float_, unsigned long) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
  "_ztoc", referenced from:
      cinder::audio::dsp::Fft::inverse(cinder::audio::BufferSpectralT<float> const_, cinder::audio::BufferT<float>*) in libcinder-iphone-sim_d.a(libcinder-iphone-sim_d.a-i386-master.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by frantic0** [comment]
Found the answer... The linker error was about finding vDSP classes: However adding Accelerate framework (Umbrella framework for vector-optimized operations) solved it.

 I guess that's what is needed to support Cinder_0.8.6. 

Cheers,
F0

**Comment by smallab** [comment]
Hi @frantic0 !
Glad you found the solution, and thanks for pointing out what needs to be done for Cinder 0.8.6 on iOS devices. I've updated the work for the Mac version which I recently needed, hadn't had the time yet to look into this one. Cheers!
